
services:
  web:
    image: leroy971/demo:${APP_VERSION} 
    environment:
      - DB_HOST=db
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
    depends_on:
      - db
    condition: service_healthy
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "python", "app.py"]
 
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
       interval: 10s
       timeout: 5s
       retries: 5