---
- name: Installer les dépendances nécessaires
  hosts: matteo_vm
  become: yes
  tasks:
    - name: Assurer que pip est installé
      apt:
        name: python3-pip
        state: present

    - name: Copier le fichier requirements.txt sur le serveur
      copy:
        src: /home/matteo/formation-devops-training/requirements.txt
        dest: /home/outscale/flask/formation-devops-training/requirements.txt

    - name: Installer les dépendances via pip
      pip:
        requirements: /home/outscale/flask/formation-devops-training/requirements.txt
        executable: pip3
