global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.3:9100']
        labels:
          hostname: 'monitoring'

      - targets: ['157.250.55.157:9100']
        labels:
          hostname: 'app1'

  - job_name: 'cadvisor'
    static_configs:     
      - targets: ['172.17.0.5:8080']
        labels:
          hostname: 'monitoring2'

      - targets: ['157.250.55.157:8080']
        labels:
          hostname: 'app1.2'

  - job_name: 'Flask'
    static_configs:     
      - targets: ['157.250.55.157:5000']
        labels:
          hostname: 'app1.1'

      

    relabel_configs:
      - source_labels: [__address__, hostname]
        regex: '^(.*):\d+;(.*)$'
        target_label: instance
        replacement: '$2:$1'
