name: CI/CD demo

on: 
  push:
    branches:
       - main
  workflow_dispatch:


jobs:
  tests_unitaires:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - 
      name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8


    - name: Install dependencies
      run: ls -l
# deployer l'application avec docker compose pour réaliser les tests unitaires
    - name: Run unit tests
      run: python test_main.py
      working-directory: ./formation-devops-training
# supprimer les containers docker créés pour réaliser les tests